server:
      port: 8080
spring:
      datasource:
              driver-class-name: com.mysql.jdbc.Driver
              username: root
              password: 1234
              url: jdbc:mysql://127.0.0.1/student?characterEncoding=utf-8&useSSL=false
      jpa:
              hibernate:
                      ddl-zuto: update